### ISSUE TITLE
set-up table schemas

### ISSUE THREAD

**Issue by omzmarlon** [omzmarlon/ManagementApp#10]
Create sql scripts for table schemas.

**Comment by omzmarlon** [comment]
@tomyang729 upload a graph for our db structure and then close this issue ⛽️

**Comment by tomyang729** [comment]
![image uploaded from ios](https://cloud.githubusercontent.com/assets/15700985/25923762/e7a63d32-3593-11e7-9de1-dbbcd41ff7fc.jpg)

Tables are circled by red. 12 in total
