### ISSUE TITLE
Project Architecture 

### ISSUE THREAD

**Issue by omzmarlon** [omzmarlon/ManagementApp#4]
Setup Project Architecture and dependencies.

**Comment by tomyang729** [comment]
Double check all the libraryDeps are compatible with each other. ie). Play Slick currently supports Slick 3.1 with Play 2.5, for Scala 2.11. So Slick 3.2 won't work

**Comment by omzmarlon** [comment]
So we have to use 3.1?

**Comment by omzmarlon** [comment]
![image uploaded from ios](https://cloud.githubusercontent.com/assets/13238492/24539697/93c2eb48-15a4-11e7-8bb7-1da6a890a070.jpg)
@tomyang729 what do you think?

**Comment by omzmarlon** [comment]
![image uploaded from ios](https://cloud.githubusercontent.com/assets/13238492/24539722/ae67192e-15a4-11e7-9ad1-607fec76f1b1.jpg)
@tomyang729 what do you think?

**Comment by tomyang729** [comment]
It looks good to me. And yes, I think we have to use Slick 3.1 (not sure why the Play docs uses 2.0.0 as example https://www.playframework.com/documentation/2.5.x/PlaySlick)

But I'll change the slick dependency to 3.1

**Comment by omzmarlon** [comment]
The documentation seems to be not sync-ed in many places..
Oh and I have made master to be a protected branch, so any push must branch out, pull request, review, before merging to master

**Comment by tomyang729** [comment]
Maybe we can re-structure our folder structure:
*play/
    ****managementapp/
    ****profile/
    ****quiz/
*core/
    ****common/ (there must be a better name)
    ****profile/
    ****quiz/

In this way, we can simplify the build.sbt (since right now there are lot of duplication, play ones and core ones are the same respectively) And we only need two modules -- play and core
Does that work? I'm not too sure

**Comment by omzmarlon** [comment]
The idea of separating each core, play into a single folder is that each of them is a single decoupled module that can be used or discarded. With above approach, we are bundling everything about play into one giant module.
There's indeed a lot of duplicate code in build.sbt. we just need to refactor out some common settings like the commonBuildSetting one

**Comment by omzmarlon** [comment]
@tomyang729 I re-thought about this issue.  I think it is perfectly ok if want to put all these separations into one module(play, or whatever we call it), but we need to at least separate these quiz/profile core/play dirs in such a way that library/framework/or any other dependencies can be separated.
Otherwise we would have disadvantage: 1.everything inside the big module depends on all included libraries(accessing code that should not be accessed, hard to manage, creates unnecessary dependencies), 2.everything share the same settings(really bad, different package may need different settings), 3. Each different modules may want to use different db access tools, machine learning tools, or any other libs/frameworks
In general I think it is good practice to at least let each dir manage its own dependencies and settings and what it wants to use in its packages, instead of let everything to be decided by its containing module

**Comment by omzmarlon** [comment]
Basic structure has been set-up by separating play and core
